### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by cie** [Hrabovszki1023/OKW#166]
java.lang.NullPointerException
	at okw.OKW_Properties.getPropertiesFilesFromResources(OKW_Properties.java:327)
	at okw.OKW_Properties.getPropertiesFilesFromResources(OKW_Properties.java:334)
	at okw.OKW_Properties.init(OKW_Properties.java:189)
	at okw.OKW_Properties.<init>(OKW_Properties.java:125)
	at okw.OKW_Properties.getInstance(OKW_Properties.java:114)
	at okw.gui.frames.FrmSeChrome.<init>(FrmSeChrome.java:52)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at okw.OKW_GetJavaClass.createInstanceByType(OKW_GetJavaClass.java:259)
	at okw.FrameObjectDictionary_Sngltn.frameScan(FrameObjectDictionary_Sngltn.java:489)
	at okw.FrameObjectDictionary_Sngltn.init(FrameObjectDictionary_Sngltn.java:370)
	at fourtest.localrunner.run.Run.reloadFrames(Run.java:172)
	... 2 more

listFiles() returns null "if this abstract pathname does not denote a directory, or if an I/O error occurs."

**Comment by Hrabovszki1023** [comment]
Done.
